# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  encoding: unicode
  adapter: postgresql
  username: shrunzzagwktdw
  password: FvCoXWwNhW3gl-NZ4A1XmhVn4w
  pool: 5
  port: 5432
  host: ec2-54-204-45-126.compute-1.amazonaws.com
  database: d1tba179du8g8f
  min_messages: WARNING

test:
  encoding: unicode
  adapter: postgresql
  username: shrunzzagwktdw
  password: FvCoXWwNhW3gl-NZ4A1XmhVn4w
  pool: 5
  port: 5432
  host: ec2-54-204-45-126.compute-1.amazonaws.com
  database: d1tba179du8g8f
  min_messages: WARNING

production:
  encoding: unicode
  adapter: postgresql
  username: shrunzzagwktdw
  password: FvCoXWwNhW3gl-NZ4A1XmhVn4w
  pool: 5
  port: 5432
  host: ec2-54-204-45-126.compute-1.amazonaws.com
  database: d1tba179du8g8f
  min_messages: WARNING
